### ISSUE TITLE
show "login failed" message,  but puppet still work

### ISSUE THREAD

**Issue by iyjian** [padlocal/wechaty-puppet-padlocal#1]
18:31:24 ERR [PuppetPadlocal] login failed
(node:82001) UnhandledPromiseRejectionWarning: Error: SubRequestCancelError: sub request has been cancelled reason: 1,
    at PuppetPadlocal.puppet.on.payload (/Users/*******/Downloads/*****_test/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetPadlocal.emit (events.js:198:13)
    at PuppetPadlocal.EventEmitter.emit (domain.js:448:20)
    at _client.api.login.then.catch (/Users/*******/Downloads/*****_test/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:207:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:82001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
on message: Message#Recalled[🗣Contact<微信团队>]
on message: Message#Recalled[🗣Contact<微信团队>]
on message: Message#Recalled[🗣Contact<微信团队>]
on message: Message#Recalled[🗣Contact<微信团队>]

**Comment by padlocal** [comment]
fixed
