### ISSUE TITLE
run await message.toContact() get an error

### ISSUE THREAD

**Issue by atorber** [padlocal/wechaty-puppet-padlocal#108]
```
          if (type === bot.Message.Type.Contact) {
            messageType = 'Contact'
            textBox = await message.toContact()
          }
```
(node:83962) UnhandledPromiseRejectionWarning: Error: not implement
    at PuppetPadlocal.messageContact (/Users/choogoo/WeChatProjects/groupmaster/wechatbot/node_modules/wechaty-puppet-padlocal/dist/puppet-padlocal.js:496:15)
    at WechatifiedMessage.toContact (/Users/choogoo/WeChatProjects/groupmaster/wechatbot/node_modules/wechaty/dist/src/user/message.js:816:53)
    at Wechaty.<anonymous> (/Users/choogoo/WeChatProjects/groupmaster/wechatbot/chatbot-pro.js:483:37)
    at Wechaty.emit (events.js:375:28)
    at Wechaty.emit (domain.js:470:12)
    at PuppetPadlocal.<anonymous> (/Users/choogoo/WeChatProjects/groupmaster/wechatbot/node_modules/wechaty/dist/src/wechaty.js:326:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:83962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Comment by padlocal** [comment]
This has not been supported yet.
