### ISSUE TITLE
接收到二维码后，持续一段时间没有扫码登录，会有报错提示，且不再推送新的二维码

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#12]
猜测是二维码过期后，触发了某些异常。

```
14:45:44 VERB [PuppetPadlocal] start login with type: QrLogin
14:45:44 VERB [PuppetPadlocal] scan event, status: Waiting, with qrcode: http://weixin.qq.com/x/obOru2-YjAKRI_JRS_OL

    ============================================
    qrcode : http://weixin.qq.com/x/obOru2-YjAKRI_JRS_OL, status: 2
    ============================================
14:50:34 ERR [PuppetPadlocal] login failed
==========error==========
Error: SubRequestCancelError: [tid:77dd522d] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:77dd522d] wechat request io error
14:50:34 SILL StateSwitch <PuppetPadlocal> off() is false
14:50:34 SILL StateSwitch <PuppetPadlocal> off() is false
14:50:34 VERB StateSwitch <PuppetPadlocal> off(pending) <- (false)
14:50:34 ERR Config ###########################
14:50:34 ERR Config unhandledRejection: TypeError: Cannot read property 'close' of undefined
    at PuppetPadlocal.stop (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:264:27)
    at _client.api.login.then.catch (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:227:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
14:50:34 ERR Config ###########################
14:50:34 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'close' of undefined)
Config TypeError: Cannot read property 'close' of undefined
    at PuppetPadlocal.stop (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:264:27)
    at _client.api.login.then.catch (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:227:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17737) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

**Comment by padlocal** [comment]
fixed.

**Comment by su-chang** [comment]
我这边刚才复测了下，还是一样的问题，是需要你那边更新一下么？

**Comment by padlocal** [comment]
需要更新客户端版本，稍等我连同其他 bug 一起发布

**Comment by padlocal** [comment]
please try wechaty-puppet-padlocal@0.2.10
