### ISSUE TITLE
发送文件下载一次后，后续再发送相同的文件，无法正常下载

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#18]
### 日志
```
15:20:25 VERB Message say(FileBox#Url<rc-upload-1602042587168-16_1602090288510_3M.txt>)
15:20:51 VERB Message static load(7854934356697007990)
15:20:51 VERB Message constructor(7854934356697007990) for class WechatifiedMessage
15:20:51 VERB Message ready()
15:20:51 VERB Puppet messagePayload(7854934356697007990)
15:20:51 SILL Puppet messagePayloadCache(7854934356697007990) cache MISS
15:20:51 WARN [SchemaMapper] Error occurred while parse message attachment: TypeError: Cannot read property 'msg' of null
    at Object.appMessageParser (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/message-parser/helpers/message-appmsg.ts:89:74)
    at process._tickCallback (internal/process/next_tick.js:68:7)
15:20:51 SILL Puppet messagePayload(7854934356697007990) cache SET
15:20:51 SILL Contact ready() @ Puppet#0<PuppetPadlocal>() with id="wxid_8kg1wdu3jvk322"
15:20:51 SILL Contact ready() isReady() true
15:20:51 SILL Contact ready() @ Puppet#0<PuppetPadlocal>() with id="Soul001001"
15:20:51 SILL Contact ready() isReady() true
msg send file: {"domain":null,"_events":{},"_eventsCount":0,"id":"7854934356697007990","payload":{"id":"7854934356697007990","timestamp":1609140028,"type":1,"fromId":"wxid_8kg1wdu3jvk322","mentionIdList":[],"text":"","toId":"Soul001001"}}
```

### 参考图片
![image](https://user-images.githubusercontent.com/9332609/103197120-6f4c8900-4920-11eb-99cc-ad6973629af8.png)

![image](https://user-images.githubusercontent.com/9332609/103197280-bf2b5000-4920-11eb-9e3b-3183df7e72b1.png)

**Comment by padlocal** [comment]
fixed

**Comment by su-chang** [comment]
仍有问题，目前再次发送相同的文件会有以下报错。

```
14:01:04 VERB Message say(FileBox#File<tsconfig.json>)
14:01:04 ERR Config ###########################
14:01:04 ERR Config unhandledRejection: VError: [tid:3978d70a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:3978d70a] wechat bad request error
    at Request._failAllPendingRequest (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/padlocal-client-ts/src/Request.ts:309:15)
    at ClientDuplexStreamImpl.Request._grpcStream.on (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/padlocal-client-ts/src/Request.ts:72:12)
    at ClientDuplexStreamImpl.emit (events.js:198:13)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:448:20)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at process.nextTick (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/@grpc/grpc-js/src/call-stream.ts:243:24)
    at process._tickCallback (internal/process/next_tick.js:61:11) [object Promise]
```

**Comment by padlocal** [comment]
fixed

**Comment by su-chang** [comment]
哪个版本？

**Comment by padlocal** [comment]
不好意思，可以用 wechaty-puppet-padlocal@0.2.19 测试

**Comment by su-chang** [comment]
已解决
