### ISSUE TITLE
无法接收到企业微信的私聊消息

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#24]
```
16:38:27 VERB [PuppetPadlocal] on push original message: {"id":"1987309256459628338","type":1,"createtime":1609144707,"fromusername":"25984982132676060@openim","tousername":"wxid_8kg1wdu3jvk322","content":"#ding","pushcontent":"苏畅 : #ding","binarypayload":"","atList":[]}
16:38:27 VERB [PuppetPadlocal] 0a133139383733303932353634353936323833333810011883b3a6ff0522183235393834393832313332363736303630406f70656e696d2a13777869645f386b6731776475336a766b33323232052364696e673a0ee88b8fe79585203a202364696e67
16:38:27 VERB Message static load(1987309256459628338)
16:38:27 VERB Message constructor(1987309256459628338) for class WechatifiedMessage
16:38:27 VERB Message ready()
16:38:27 VERB Puppet messagePayload(1987309256459628338)
16:38:27 SILL Puppet messagePayloadCache(1987309256459628338) cache MISS
16:38:27 ERR Config ###########################
16:38:27 ERR Config unhandledRejection: Error: empty roomId and empty fromId!
    at Object.padLocalMessageToWechaty (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/schema-mapper/index.ts:95:11)
    at PuppetPadlocal.messageRawPayloadParser (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1098:12)
    at PuppetPadlocal.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/src/puppet.ts:855:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/dist/src/puppet.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
16:38:27 ERR Config ###########################
16:38:27 ERR Config process.on(unhandledRejection) promise.catch(empty roomId and empty fromId!)
Config Error: empty roomId and empty fromId!
    at Object.padLocalMessageToWechaty (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/schema-mapper/index.ts:95:11)
    at PuppetPadlocal.messageRawPayloadParser (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1098:12)
    at PuppetPadlocal.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/src/puppet.ts:855:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/dist/src/puppet.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19663) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 16)
```

**Comment by padlocal** [comment]
fix in wechaty-puppet-padlocal@0.2.13

**Comment by su-chang** [comment]
现在可以接收到消息

但是文本消息中的文本内容无法显示，接收到的图片消息无法进行转发。
