### ISSUE TITLE
无法获取到企业微信群的群头像

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#25]
```
16:45:39 VERB Room avatar()
16:45:39 ERR Config ###########################
16:45:39 ERR Config unhandledRejection: TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at Function.fromUrl (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/file-box/src/file-box.ts:69:25)
    at PuppetPadlocal.roomAvatar (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1007:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
16:45:39 ERR Config ###########################
16:45:39 ERR Config process.on(unhandledRejection) promise.catch(Invalid URL: )
Config { TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at Function.fromUrl (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/file-box/src/file-box.ts:69:25)
    at PuppetPadlocal.roomAvatar (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1007:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) input: '' }
(node:20628) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by su-chang** [comment]
```
14:10:34 VERB Room avatar()
14:10:34 ERR Config ###########################
14:10:34 ERR Config unhandledRejection: TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at Function.fromUrl (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/file-box/src/file-box.ts:69:25)
    at PuppetPadlocal.roomAvatar (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1028:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
```

**Comment by padlocal** [comment]
需要client 更新，还没有发布的。更新后我再来通知

**Comment by padlocal** [comment]
fixed in wechaty-puppet-padlocal@0.2.16

**Comment by su-chang** [comment]
0.2.16仍是一样的报错
