### ISSUE TITLE
目前不支持自动通过群邀请

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#28]
```
16:54:08 VERB RoomInvitation accept()
16:54:08 ERR Config ###########################
16:54:08 ERR Config unhandledRejection: Error: Accept room invitation is not unsupported
    at PuppetPadlocal.roomInvitationAccept (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1061:11)
    at WechatifiedRoomInvitation.accept (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty/src/user/room-invitation.ts:123:31)
    at /Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:165:26
    at step (/Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:32:23)
    at Object.next (/Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:13:53)
    at /Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:3:12)
    at Wechaty.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPuppet/index.ts:163:48)
    at Wechaty.emit (events.js:198:13)
    at Wechaty.EventEmitter.emit (domain.js:448:20)
    at PuppetPadlocal.puppet.on (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty/src/wechaty.ts:506:18)
    at PuppetPadlocal.emit (events.js:198:13)
    at PuppetPadlocal.EventEmitter.emit (domain.js:448:20)
    at PuppetPadlocal._onPushMessage (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1300:14)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
```

**Comment by padlocal** [comment]
Fixed wechaty-puppet-padlocal@0.2.27
