### ISSUE TITLE
企业微信添加bot的好友请求无法转换为对应的friendship事件

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#29]
```
17:00:14 VERB [PuppetPadlocal] on push original message: {"id":"1781282098155551803","type":65,"createtime":1609146014,"fromusername":"fmessage","tousername":"wxid_8kg1wdu3jvk322","content":"<msg fromusername=\"25984985460320147@openim\" fromnickname=\"是不是改个名\" content=\"我是句子科技的是不是改个名，添加我的企业微信与我联系吧。\" fullpy=\"shibushigaigeming\" shortpy=\"SBSGGM\" imagestatus=\"4\" bigheadimgurl=\"http://wework.qpic.cn/bizmail/YtDta1u3BCtIicnAsEOYJrYkScJpGFo09udzBRwJic7sWlJcjs7tJhAw/0\" smallheadimgurl=\"http://wework.qpic.cn/bizmail/YtDta1u3BCtIicnAsEOYJrYkScJpGFo09udzBRwJic7sWlJcjs7tJhAw/0\" ticket=\"v1_f68005637f475fe4a877dfb13b0010d59cb1674b8ed593b4103db7f37a7f2b2f76f831f3df22c83509c80d19e4103d9477a5cca59974668f65916bcd4aa1a2207f8681242dd51f20a2a909f4b27065f605480e95d835abb1d25a2b2744caf17c6df5a23e7601ea4017a3f169082941ee72ef2a702ae741d637362dd801138e4cfe22a4de8bf33d2ca08a332a9455c5815af3fefd604041b14d0c24447992360fa426c409f7d0f851cff1fc5864ff2e352997658bcbeb0c8fb33f5df9c6616be25bc4292d44359355e474f6036bea368a\" opcode=\"2\" openimappid=\"3552365301\" scene=\"30\" sourceusername=\"\" sourcenickname=\"\" />\n","pushcontent":"","binarypayload":"","atList":[]}
17:00:14 VERB [PuppetPadlocal] 0a13313738313238323039383135353535313830331041189ebda6ff052208666d6573736167652a13777869645f386b6731776475336a766b33323232c1073c6d73672066726f6d757365726e616d653d223235393834393835343630333230313437406f70656e696d222066726f6d6e69636b6e616d653d22e698afe4b88de698afe694b9e4b8aae5908d2220636f6e74656e743d22e68891e698afe58fa5e5ad90e7a791e68a80e79a84e698afe4b88de698afe694b9e4b8aae5908defbc8ce6b7bbe58aa0e68891e79a84e4bc81e4b89ae5beaee4bfa1e4b88ee68891e88194e7b3bbe590a7e38082222066756c6c70793d22736869627573686967616967656d696e67222073686f727470793d2253425347474d2220696d6167657374617475733d2234222062696768656164696d6775726c3d22687474703a2f2f7765776f726b2e717069632e636e2f62697a6d61696c2f59744474613175334243744969636e4173454f594a72596b53634a7047466f303975647a4252774a69633773576c4a636a7337744a6841772f302220736d616c6c68656164696d6775726c3d22687474703a2f2f7765776f726b2e717069632e636e2f62697a6d61696c2f59744474613175334243744969636e4173454f594a72596b53634a7047466f303975647a4252774a69633773576c4a636a7337744a6841772f3022207469636b65743d2276315f663638303035363337663437356665346138373764666231336230303130643539636231363734623865643539336234313033646237663337613766326232663736663833316633646632326338333530396338306431396534313033643934373761356363613539393734363638663635393136626364346161316132323037663836383132343264643531663230613261393039663462323730363566363035343830653935643833356162623164323561326232373434636166313763366466356132336537363031656134303137613366313639303832393431656537326566326137303261653734316436333733363264643830313133386534636665323261346465386266333364326361303861333332613934353563353831356166336665666436303430343162313464306332343434373939323336306661343236633430396637643066383531636666316663353836346666326533353239393736353862636265623063386662333366356466396336363136626532356263343239326434343335393335356534373466363033366265613336386122206f70636f64653d223222206f70656e696d61707069643d223335353233363533303122207363656e653d2233302220736f75726365757365726e616d653d222220736f757263656e69636b6e616d653d2222202f3e0a
17:00:14 VERB Message static load(1781282098155551803)
17:00:14 VERB Message constructor(1781282098155551803) for class WechatifiedMessage
17:00:14 VERB Message ready()
17:00:14 VERB Puppet messagePayload(1781282098155551803)
17:00:14 SILL Puppet messagePayloadCache(1781282098155551803) cache MISS
17:00:14 ERR Config ###########################
17:00:14 ERR Config unhandledRejection: Error: unsupported type: 65
    at Object.convertMessageType (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/message-parser/helpers/message.ts:57:13)
    at Object.padLocalMessageToWechaty (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/schema-mapper/index.ts:20:16)
    at PuppetPadlocal.messageRawPayloadParser (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1098:12)
    at PuppetPadlocal.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/src/puppet.ts:855:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/dist/src/puppet.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
17:00:14 ERR Config ###########################
17:00:14 ERR Config process.on(unhandledRejection) promise.catch(unsupported type: 65)
Config Error: unsupported type: 65
    at Object.convertMessageType (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/message-parser/helpers/message.ts:57:13)
    at Object.padLocalMessageToWechaty (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/padlocal/schema-mapper/index.ts:20:16)
    at PuppetPadlocal.messageRawPayloadParser (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1098:12)
    at PuppetPadlocal.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/src/puppet.ts:855:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet/dist/src/puppet.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20824) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
```

**Comment by padlocal** [comment]
fixed in wechaty-puppet-padlocal@0.2.16
