### ISSUE TITLE
将群成员踢出群组报错

### ISSUE THREAD

**Issue by hcolde** [padlocal/wechaty-puppet-padlocal#35]
踢出群成员需要bot是群主或群管理员，但只发现获取当前群主信息的接口：Room.owner()。
所以当bot是群管理员或群众时，无法判断bot是否有踢人的权限。
建议加入一个获取群管理员的接口。

以下报错是当bot为群众时踢人引发的，但当手机端每次点进这个群时，总会再次报错

```shell
(node:62798) UnhandledPromiseRejectionWarning: VError: [tid:20ff7a43] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:20ff7a43] wechat bad request error
    at Request._failAllPendingRequest (/Users/colde/Develop/reviewer/node_modules/padlocal-client-ts/src/Request.ts:309:15)
    at ClientDuplexStreamImpl.<anonymous> (/Users/colde/Develop/reviewer/node_modules/padlocal-client-ts/src/Request.ts:72:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:486:12)
    at Object.onReceiveStatus (/Users/colde/Develop/reviewer/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/Users/colde/Develop/reviewer/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /Users/colde/Develop/reviewer/node_modules/@grpc/grpc-js/src/call-stream.ts:243:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:62798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by padlocal** [comment]
已修复。这种情况下，会在返回的请求中添加错误信息。
