### ISSUE TITLE
先下载后转发图片/文件/小程序，可以转发成功，但有异常报错提示

### ISSUE THREAD

**Issue by su-chang** [padlocal/wechaty-puppet-padlocal#36]
加载到的msgId与实际接收消息的msgId不符
```
14:38:35 VERB Message forward(Contact<苏畅>)
14:38:35 VERB Message static load(641510417)
14:38:35 VERB Message constructor(641510417) for class WechatifiedMessage
14:38:35 VERB Message ready()
14:38:35 VERB Puppet messagePayload(641510417)
14:38:35 SILL Puppet messagePayloadCache(641510417) cache MISS
14:38:35 ERR Message forward(Contact<苏畅>) exception: Error: can not find message in cache for messageId: 641510417
14:38:35 ERR Config ###########################
14:38:35 ERR Config unhandledRejection: Error: can not find message in cache for messageId: 641510417
    at PuppetPadlocal.messageRawPayload (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1141:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) [object Promise]
14:38:35 ERR Config ###########################
14:38:35 ERR Config process.on(unhandledRejection) promise.catch(can not find message in cache for messageId: 641510417)
Config Error: can not find message in cache for messageId: 641510417
    at PuppetPadlocal.messageRawPayload (/Users/suchang/Desktop/PROJECT/Test/testPuppet/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1141:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:402) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
```

**Comment by padlocal** [comment]
Fixed
