### ISSUE TITLE
新注册微信不能登陆报“SERVER_ERROR: 2 UNKNOWN: [tid:bec7b588] wechat bad request erro”

### ISSUE THREAD

**Issue by biofer** [padlocal/wechaty-puppet-padlocal#46]
新注册微信账户（1月28号注册）不能登陆。
```
export WECHATY_LOG="verbose"

export WECHATY_PUPPET="wechaty-puppet-padlocal"
export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_XXXXX"

export WECHATY_PUPPET_SERVER_PORT="9001"
export WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c-e03dd1974d9a"

docker run -ti \
  --name wechaty_puppet_service_token_gateway \
  --rm \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADLOCAL_TOKEN \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_TOKEN \
  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
  wechaty/wechaty:0.56
```
log:
```
15:04:29 VERB [Request] [tid:57199243] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"766ccd7667234765a957bc5c8355d9fb","payload":"F/EDArvd5+kUaoA6++dsCtti06vb8PCg4lCpXcA3QVUeikLcKyBsQbBjmhkmkH0r3yeMey+zBOTWqFuTXpe4QbV0984aqbjdB6usMirOlFy3IOrFQGFLQNt82X7oD5LtdWGTe3IIdkDudl07ePxgGX1/k0ayEf2fkj3UZzLT2Ti41BzwNrM7b671uP6A5sMWy9HP1CMTNNceBV03rnO3hZ8tF5asttAsDVxRnAO18V2cSv3pIReykU7mvxuPqZ/W+JLo1qL16uly4rqsupqE0OQYNRJXzoK+5RpJxwbL3BNyre6SUaLu6JDCV4XnPZ66O3XADYX9+AhWrVK2ts9pOO5VLODDBgs1nUvtk+pii/w+b5o7opvrS7jpyUpPJpPMp68HfnI1Rpz9OGF7zqbn7fzw8SSaHw6UkWOkvYaiFOUx77+Dexx4McU4JSJZwZyE/Nrre+CuJ2sKSMAyJqI6+vP+qWS7P5n6+1lyNo4CGxcVIU9sJ+5Xek37b61Qa7x+BFCl56NqUKGpKgxLJM34OzMchWjldioqLvDBJgJ/ONDxs42D9rDi+U0iJ7XzXq8PG9w8twu09x++MX+DU/ee8DpMsXNEjc/A26VH3IDSAiAUoyPOFEgg2HtbhKtxcqFzD443eQOv2sVtt6NTU+S+g72AilhxbeiPaJ8Fn0iJYjAS92lX86X5IKOIf1KksUgVQtR04AlvdIEIYI7KaXQasdTABZF8S7+MzJPGq5h9OTP1DFWLjIW8iwxabfekZha1CyfNPbBecc9gB7USUaOdZT0CpXKUGy2S1B7L/hmM4lJjpXGPzFit4VjMzV9/I9vwJUbr53LUkqGWClXCdkwiHc6YgdwKgJZlPAYfBF1MPn2Uh4sENyX3XUWW//M14EpxWXMCTGes8jMgigAWMslgcXqAjGXPkraeNl4uhwgTLHA="}
15:04:29 VERB [Request] [tid:57199243] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"c7bdcee3a2c44c1ab7607cd4fcb1e1cc"}]}
15:04:29 VERB [Request] [tid:bec7b588] send event to server, seq:undefined, ack:5, type: 11, payload: {"longlinkresponse":{}}
15:04:29 ERR [PuppetPadlocal] login failed: VError: [tid:bec7b588] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:bec7b588] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
15:04:29 VERB StateSwitch <PuppetPadlocal> off(pending) <- (false)
15:04:29 VERB [LongLink] [766ccd7667234765a957bc5c8355d9fb] longlink shutdown
15:04:29 VERB [LongLink] [766ccd7667234765a957bc5c8355d9fb] longlink stopHeartbeat
15:04:29 VERB StateSwitch <PuppetPadlocal> off(true) <- (pending)
15:04:30 VERB StateSwitch <PuppetPadlocal> on(pending) <- (false)
15:04:30 VERB [Request] [tid:559eab84] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
15:04:30 VERB [Request] [tid:559eab84] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"long.weixin.qq.com","port":80},"reconnectimmediately":false}}
```
用注册时间比较长的微信可以登陆。
不知道该怎么调试。

**Comment by huan** [comment]
What IP are you using with your PadLocal Wechaty bot?

There is a known issue that the PadLocal can only be used on IP addresses in China.

If you are using a server outside China, use a VPS in China might fix your problem.

**Comment by biofer** [comment]
Yes, I am sure use the IP addresses in China.
I just register a wechat account and test on docker(wechaty/wechaty:0.56), It did not work.
I also test serval old account, and it work.

**Comment by xiaogan18** [comment]
I got same problem, looking forward solutions

**Comment by padlocal** [comment]
working on this

**Comment by wangzheooo** [comment]
同样的问题,不知怎么解决

**Comment by paulhybryant** [comment]
I ran into the same issue. I can log in with my old wechat account, but not a newly registered one. Both logins were done on the same machine so this is not an IP problem.

**Comment by padlocal** [comment]
hey guys，looking for volunteers to test this issue. If you are interested, reply this thread to let me know.

**Comment by paulhybryant** [comment]
I am interested. @padlocal

**Comment by iivveess** [comment]
@padlocal 
I can help.
Wechat me anytime.

**Comment by Jesn** [comment]
@padlocal 
I have a new wechat Account can't login by padlocal，Ready to  test！

**Comment by padlocal** [comment]
Fixed, anyone interested can contact us via email (oxddoxdd#gmail.com) or wechat
