### ISSUE TITLE
exception when trying to add a Contact into a tag. 

### ISSUE THREAD

**Issue by wenzai007** [padlocal/wechaty-puppet-padlocal#53]
copied from this https://github.com/wechaty/wechaty/issues/2140

while trying to use the sdk of add in tag.ts

```await tag.add(contact);```

I got below exception, is this expected server error?? So Tecent does not allow this API? Or I miss something?

00:12:59 ERR Tag add() exception: [tid:d8a97571] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d8a97571] wechat bad request error
(node:46652) UnhandledPromiseRejectionWarning: Error: add error : SubRequestCancelError: [tid:d8a97571] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d8a97571] wechat bad request error
at WechatifiedTag.add (/Users/Knight/Working/github/padlocal-tagbased-bot/node_modules/wechaty/src/user/tag.ts:182:13)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:46652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Maybe padlocal does not support this?  Could we need to support this feature？

**Comment by wenzai007** [comment]
dup with https://github.com/wechaty/wechaty/issues/2140
