### ISSUE TITLE
Can't Login - Wechat Request IO error

### ISSUE THREAD

**Issue by InfTkm** [padlocal/wechaty-puppet-padlocal#59]
After scanning the QR code, login confirmed, this error shows up.

Error message:
(node:7775) UnhandledPromiseRejectionWarning: VError: [tid:d195bacb] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d195bacb] wechat request io error
    at Request._failAllPendingRequest (/home/bitnami/optionbot/node_modules/padlocal-client-ts/dist/Request.js:262:19)
    at ClientDuplexStreamImpl.<anonymous> (/home/bitnami/optionbot/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/home/bitnami/optionbot/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
    at Object.onReceiveStatus (/home/bitnami/optionbot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/bitnami/optionbot/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by padlocal** [comment]
Close duplicated issue : https://github.com/padlocal/wechaty-puppet-padlocal/issues/60. Discuss on that thread please.
