### ISSUE TITLE
padlocal puppet service token gateway crash with error

### ISSUE THREAD

**Issue by su27k-2003** [padlocal/wechaty-puppet-padlocal#74]
padlocal puppet service token gateway crashes every time with the error below. Please investigate. Thanks.

Background
The token server has been built in GCP HongKong zone and worked well until had a issue (puppet login failed #60) recently. 
After @padlocal updated issue #66, I tried to test it but found the token gateway could not start properly with the error message below.

Error message
14:32:41 ERR [PuppetPadlocal] login failed: VError: [tid:1cd1b06f] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:1cd1b06f] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
...
14:32:42 VERB StateSwitch <PuppetPadlocal> on(pending) <- (false)
corrupted size vs. prev_size
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! wechaty@0.56.6 io-client: `ts-node bin/io-client`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the wechaty@0.56.6 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2021-04-25T14_32_43_321Z-debug.log

Version Info
Docker Container for Wechaty v0.56.6 with Node.js v12.20.1

**Comment by suntong** [comment]
Maybe related so I'm reporting mine here as well. 

I don't know if the padlocal puppet service token gateway crashes but from my client side, I'm getting this:

```
(node:117979) UnhandledPromiseRejectionWarning: VError: [tid:0031dc53] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:0031dc53] wechat bad request error
    at Request._failAllPendingRequest (/path/to/node_modules/padlocal-client-ts/dist/Request.js:262:19)
    at ClientDuplexStreamImpl.<anonymous> (/path/to/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /path/to/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)





SubRequestCancelError [VError]: [tid:1b1a2ee2] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:1b1a2ee2] wechat bad request error
    at Request._failAllPendingRequest (/path/to/node_modules/padlocal-client-ts/dist/Request.js:262:19)
    at ClientDuplexStreamImpl.<anonymous> (/path/to/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /path/to/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  jse_shortmsg: '[tid:1b1a2ee2] request has been cancelled for reason: SERVER_ERROR',
  jse_cause: Error: 2 UNKNOWN: [tid:1b1a2ee2] wechat bad request error
      at Object.callErrorFromStatus (/path/to/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client.js:387:49)
      at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
      at /path/to/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
      at processTicksAndRejections (internal/process/task_queues.js:75:11) {
    code: 2,
    details: '[tid:1b1a2ee2] wechat bad request error',
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  },
  jse_info: {},
  reason: 1
}


SubRequestCancelError [VError]: [tid:221abf79] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:221abf79] wechat bad request error
    at Request._failAllPendingRequest (/path/to/node_modules/padlocal-client-ts/dist/Request.js:262:19)
    at ClientDuplexStreamImpl.<anonymous> (/path/to/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
    at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /path/to/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  jse_shortmsg: '[tid:221abf79] request has been cancelled for reason: SERVER_ERROR',
  jse_cause: Error: 2 UNKNOWN: [tid:221abf79] wechat bad request error
      at Object.callErrorFromStatus (/path/to/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client.js:387:49)
      at Object.onReceiveStatus (/path/to/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
      at /path/to/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
      at processTicksAndRejections (internal/process/task_queues.js:75:11) {
    code: 2,
    details: '[tid:221abf79] wechat bad request error',
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  },
  jse_info: {},
  reason: 1
}
20:30:51 WARN [PuppetPadlocal] stop() is called on a OFF puppet. await ready(off) and return.
Goodbye
```

They are not from a single session, but they are the fist message the bot got when it logs in. I have a loop, so I'm keep getting it.

**Comment by padlocal** [comment]
Thanks for your feedback, we are investigating

**Comment by padlocal** [comment]
Fixed, please have a try :)
