### ISSUE TITLE
[Need Help] Session closed

### ISSUE THREAD

**Issue by magus0219** [padlocal/wechaty-puppet-padlocal#78]
Hi,

I am testing wechaty with this puppet,

After logged in everything seems works until logger complains session closed, 

```
18:17:50 WARN PuppetWeChatBridge proxyWechaty() noWechaty exception: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
18:17:50 ERR PuppetWeChatBridge roomList() exception: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer/src/common/Connection.ts:251:9)
    at next (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:32:41)
    at CDPSession.send (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:65:16)
    at ExecutionContext._evaluateInternal (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer/src/common/ExecutionContext.ts:252:44)
    at ExecutionContext.evaluate (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer/src/common/ExecutionContext.ts:138:23)
    at DOMWorld.evaluate (/Users/magus0219/Documents/WebstormProjects/tifa/node_modules/puppeteer/src/common/DOMWorld.ts:163:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Anyone knows the reason and how to fix?

Thanks a lot.

**Comment by magus0219** [comment]
this is my mistake, I use wechat not padlocal instead.
