### ISSUE TITLE
issue unknow, bot looks like stuck

### ISSUE THREAD

**Issue by why2lyj** [padlocal/wechaty-puppet-padlocal#80]
using python-wechaty 

did nothing, bot looks like stuck. I restart bot but still meeting this issue.  

```shell
05:48:41 VERB [Request] [tid:c753d94b] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
05:48:41 VERB [Request] [tid:c753d94b] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"69d47374782047c39887545bdca5391b","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
05:48:41 VERB [Request] [tid:01c24e30] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"69d47374782047c39887545bdca5391b"}
05:48:41 VERB [Request] [tid:01c24e30] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACD1Pf//XrlhM85SBlJ5rcQM9m440/jIEsyXkNDyV2WyVw=="}
05:48:41 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f1030020f53dffff5eb96133ce52065279adc40cf66e38d3f8c812cc9790d0f25765b257
05:48:41 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f10300204f98374b6488b0bc56698dfaf7e13d22e3239d13c431936788c2dbeb9db1dc31
05:48:41 VERB [Request] [tid:6e6d7104] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACBPmDdLZIiwvFZpjfr34T0i4yOdE8Qxk2eIwtvrnbHcMQ=="}
05:48:41 VERB [Request] [tid:6e6d7104] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"69d47374782047c39887545bdca5391b"}]}
05:48:41 VERB [Request] [tid:c753d94b] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
05:48:41 VERB [Request] [tid:c753d94b] receive event from server, seq:0 ack:1, type:87, payload:{}
05:51:21 VERB [Request] [tid:a6e557d3] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
05:51:21 VERB [Request] [tid:a6e557d3] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"c4cca841e6a24fbb961af4f9ea5bf814","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
05:51:21 VERB [Request] [tid:7acae3f4] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"c4cca841e6a24fbb961af4f9ea5bf814"}
05:51:21 VERB [Request] [tid:7acae3f4] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACBpchcZbb/cf9x+qZ6aDKb86OtQlJ/mDvmK8XHOWMSyxQ=="}
05:51:21 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f1030020697217196dbfdc7fdc7ea99e9a0ca6fce8eb50949fe60ef98af171ce58c4b2c5
05:51:21 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f1030020dfa8e63da4f3063d039cc659944bd1252255668d4ce372fe4984d9e5555b8702
05:51:21 VERB [Request] [tid:bbd75a46] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACDfqOY9pPMGPQOcxlmUS9ElIlVmjUzjcv5JhNnlVVuHAg=="}
05:51:21 VERB [Request] [tid:bbd75a46] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"c4cca841e6a24fbb961af4f9ea5bf814"}]}
05:51:21 VERB [Request] [tid:a6e557d3] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
05:51:21 VERB [Request] [tid:a6e557d3] receive event from server, seq:0 ack:1, type:87, payload:{}
05:54:01 VERB [Request] [tid:7281ad46] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
05:54:01 VERB [Request] [tid:7281ad46] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"dbe698ea3426434d856a95123b236c6a","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
05:54:01 VERB [Request] [tid:26068af0] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"dbe698ea3426434d856a95123b236c6a"}
05:54:01 VERB [Request] [tid:26068af0] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACB4mAt5zv7cPOhygCrwPJBKAEm1FEp/oRLVOvGRy/Btpw=="}
05:54:01 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f103002078980b79cefedc3ce872802af03c904a0049b5144a7fa112d53af191cbf06da7
05:54:02 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f1030020f87c9bb2a303c014fb575942645ddbbf76f12012933689cec1e6b54d338c42c0
05:54:02 VERB [Request] [tid:76e832c2] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACD4fJuyowPAFPtXWUJkXdu/dvEgEpM2ic7B5rVNM4xCwA=="}
05:54:02 VERB [Request] [tid:76e832c2] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"dbe698ea3426434d856a95123b236c6a"}]}
05:54:02 VERB [Request] [tid:7281ad46] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
05:54:02 VERB [Request] [tid:7281ad46] receive event from server, seq:0 ack:1, type:87, payload:{}
05:56:42 VERB [Request] [tid:255ee07a] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
05:56:42 VERB [Request] [tid:255ee07a] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"c4c3e3f94bab4be38839530afc545f57","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
05:56:42 VERB [Request] [tid:193ca93d] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"c4c3e3f94bab4be38839530afc545f57"}
05:56:42 VERB [Request] [tid:193ca93d] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACCcVQuqHmDccFCdDP1fCUzICiRSC+IosUCiXIKkCUqZnw=="}
05:56:42 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f10300209c550baa1e60dc70509d0cfd5f094cc80a24520be228b140a25c82a4094a999f
05:56:42 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f1030020ddf7f14c5f4b832e5f4749ecae2cbf114d0ba35ea9eb9ab3b3e96a5212966381
05:56:42 VERB [Request] [tid:135e3455] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACDd9/FMX0uDLl9HSeyuLL8RTQujXqnrmrOz6WpSEpZjgQ=="}
05:56:42 VERB [Request] [tid:135e3455] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"c4c3e3f94bab4be38839530afc545f57"}]}
05:56:42 VERB [Request] [tid:255ee07a] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
05:56:42 VERB [Request] [tid:255ee07a] receive event from server, seq:0 ack:1, type:87, payload:{}
05:59:22 VERB [Request] [tid:8118d591] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
05:59:22 VERB [Request] [tid:8118d591] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"eb3187082ff646cebb6d59d5c2ac2fec","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
05:59:22 VERB [Request] [tid:3e2c0c6f] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"eb3187082ff646cebb6d59d5c2ac2fec"}
05:59:22 VERB [Request] [tid:3e2c0c6f] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACD7MsxP+iCBlb1gBQPhvuYdyUhR87ExYMrFOql5Sizn/g=="}
05:59:22 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f1030020fb32cc4ffa208195bd600503e1bee61dc94851f3b13160cac53aa9794a2ce7fe
05:59:22 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f103002074701761a6bf632fbe49a662507c6c4850d038fa42df77fe3be633b7cadef21b
05:59:22 VERB [Request] [tid:4dcbcef3] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACB0cBdhpr9jL75JpmJQfGxIUNA4+kLfd/475jO3yt7yGw=="}
05:59:22 VERB [Request] [tid:4dcbcef3] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"eb3187082ff646cebb6d59d5c2ac2fec"}]}
05:59:22 VERB [Request] [tid:8118d591] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
05:59:22 VERB [Request] [tid:8118d591] receive event from server, seq:0 ack:1, type:87, payload:{}
06:02:02 VERB [Request] [tid:315c3e19] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
06:02:02 VERB [Request] [tid:315c3e19] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"d0962fda56b64f29bb8cdcaaad7d553f","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
06:02:02 VERB [Request] [tid:2f2af72a] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"d0962fda56b64f29bb8cdcaaad7d553f"}
06:02:02 VERB [Request] [tid:2f2af72a] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACB//5XDIf5boafVUIZsDa2H1TABaAZjBCdR/t4wypBuVg=="}
06:02:02 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f10300207fff95c321fe5ba1a7d550866c0dad87d53001680663042751fede30ca906e56
06:02:02 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f10300204c3c422882a1d15ca6273c9a58fbc3fdea0eb937ee51508cef7ff0233e8f5f2b
06:02:02 VERB [Request] [tid:472bc9b0] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACBMPEIogqHRXKYnPJpY+8P96g65N+5RUIzvf/AjPo9fKw=="}
06:02:02 VERB [Request] [tid:472bc9b0] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"d0962fda56b64f29bb8cdcaaad7d553f"}]}
06:02:02 VERB [Request] [tid:315c3e19] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
06:02:02 VERB [Request] [tid:315c3e19] receive event from server, seq:0 ack:1, type:87, payload:{}
06:04:42 VERB [Request] [tid:6e04790e] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
06:04:42 VERB [Request] [tid:6e04790e] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"300949322fc946b0a9297a22e232fcee","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
06:04:42 VERB [Request] [tid:fcf3aa27] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"300949322fc946b0a9297a22e232fcee"}
06:04:42 VERB [Request] [tid:fcf3aa27] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACC97sCdHHU3PFTAiEky2ho6shx6n30L0w+wRU8CYUsM2w=="}
06:04:42 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f1030020bdeec09d1c75373c54c0884932da1a3ab21c7a9f7d0bd30fb0454f02614b0cdb
06:04:42 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f1030020eefe1bdfc8ce8296b7cb8626ca0dcb8b985aecdd980267d6fcc30ed8ae75b213
06:04:42 VERB [Request] [tid:8b3aead8] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACDu/hvfyM6ClrfLhibKDcuLmFrs3ZgCZ9b8ww7YrnWyEw=="}
06:04:42 VERB [Request] [tid:8b3aead8] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"300949322fc946b0a9297a22e232fcee"}]}
06:04:42 VERB [Request] [tid:6e04790e] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
06:04:43 VERB [Request] [tid:6e04790e] receive event from server, seq:0 ack:1, type:87, payload:{}
06:07:23 VERB [Request] [tid:45da85cb] send event to server, seq:1, ack:undefined, type: 86, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b"}
06:07:23 VERB [Request] [tid:45da85cb] receive event from server, seq:1 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"f771d2e4b667461994b3b92f7968683c","longlinkid":"056756c41e0e45b381dc474e7ef0f53b","initphase":false}}
06:07:23 VERB [Request] [tid:0635f58a] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","messageid":"f771d2e4b667461994b3b92f7968683c"}
06:07:23 VERB [Request] [tid:0635f58a] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACD0sTYYVGhlnPqN998nJDfyofiiimAaLw3cnjj3VfD3gg=="}
06:07:23 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket send:17f1030020f4b136185468659cfa8df7df272437f2a1f8a28a601a2f0ddc9e38f755f0f782
06:07:23 VERB [LongLink] [056756c41e0e45b381dc474e7ef0f53b] socket recv:17f10300201357df1f64b25911981e0d741a2a7f2b1e513d482c168b2a149f385ed7da596d
06:07:23 VERB [Request] [tid:e5022dbd] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"056756c41e0e45b381dc474e7ef0f53b","payload":"F/EDACATV98fZLJZEZgeDXQaKn8rHlE9SCwWiyoUnzhe19pZbQ=="}
06:07:23 VERB [Request] [tid:e5022dbd] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"f771d2e4b667461994b3b92f7968683c"}]}
06:07:23 VERB [Request] [tid:45da85cb] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
06:07:23 VERB [Request] [tid:45da85cb] receive event from server, seq:0 ack:1, type:87, payload:{}
06:09:37 WARN Io initWebSocket() close event[1006: ]
06:09:37 VERB Io reconnect()
06:09:37 WARN Io reconnect() will reconnect after 0 s
06:09:37 VERB Io initWebSocket()
06:09:37 WARN Io initWebSocket() error event[connect ECONNREFUSED 13.76.100.124:443]
06:09:37 VERB Io send() without a connected websocket, eventBuffer.length = 1
06:09:37 WARN Io initWebSocket() close event[1006: ]
06:09:37 VERB Io reconnect()
06:09:37 WARN Io reconnect() will reconnect after 0 s
06:09:37 ERR Config ###########################
06:09:37 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:37 ERR Config ###########################
06:09:37 ERR Config ###########################
06:09:37 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:37 ERR Config ###########################
06:09:37 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
06:09:37 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
(node:40) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
06:09:37 VERB Io initWebSocket()
06:09:37 WARN Io initWebSocket() error event[connect ECONNREFUSED 13.76.100.124:443]
06:09:37 VERB Io send() without a connected websocket, eventBuffer.length = 2
06:09:37 WARN Io initWebSocket() close event[1006: ]
06:09:37 VERB Io reconnect()
06:09:37 WARN Io reconnect() will reconnect after 0 s
06:09:37 ERR Config ###########################
06:09:37 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:37 ERR Config ###########################
06:09:37 ERR Config ###########################
06:09:37 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:37 ERR Config ###########################
06:09:37 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
06:09:37 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
(node:40) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
06:09:37 VERB Io initWebSocket()
06:09:38 WARN Io initWebSocket() error event[connect ECONNREFUSED 13.76.100.124:443]
06:09:38 VERB Io send() without a connected websocket, eventBuffer.length = 3
06:09:38 WARN Io initWebSocket() close event[1006: ]
06:09:38 VERB Io reconnect()
06:09:38 WARN Io reconnect() will reconnect after 0 s
06:09:38 ERR Config ###########################
06:09:38 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:38 ERR Config ###########################
06:09:38 ERR Config ###########################
06:09:38 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:38 ERR Config ###########################
06:09:38 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
06:09:38 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
(node:40) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
06:09:38 VERB Io initWebSocket()
06:09:39 WARN Io initWebSocket() error event[connect ECONNREFUSED 13.76.100.124:443]
06:09:39 VERB Io send() without a connected websocket, eventBuffer.length = 4
06:09:39 WARN Io initWebSocket() close event[1006: ]
06:09:39 VERB Io reconnect()
06:09:39 WARN Io reconnect() will reconnect after 0 s
06:09:39 ERR Config ###########################
06:09:39 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:39 ERR Config ###########################
06:09:39 ERR Config ###########################
06:09:39 ERR Config unhandledRejection: Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) [object Promise]
06:09:39 ERR Config ###########################
06:09:39 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
06:09:39 ERR Config process.on(unhandledRejection) promise.catch(connect ECONNREFUSED 13.76.100.124:443)
Config Error: connect ECONNREFUSED 13.76.100.124:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.76.100.124',
  port: 443
}
(node:40) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)

```

**Comment by Jesn** [comment]
同样遇到类似的情况
```
05:05:04 VERB EventStreamManager grpcEmit(EVENT_TYPE_READY[23], {"data":"ready"})
05:05:04 WARN EventStreamManager grpcEmit(23, {"data":"ready"}) this.eventStream is undefined.
05:05:08 WARN Io initWebSocket() close event[1006: ]
05:05:08 VERB Io reconnect()
05:05:08 WARN Io reconnect() will reconnect after 0 s
05:05:08 VERB Io initWebSocket()
05:05:11 VERB Io send() without a connected websocket, eventBuffer.length = 1
05:05:11 WARN Io initWebSocket() error event[Client network socket disconnected before secure TLS connection was established]
05:05:11 WARN Io initWebSocket() close event[1006: ]
05:05:11 VERB Io reconnect()
05:05:11 WARN Io reconnect() will reconnect after 0 s
05:05:11 ERR Config ###########################
05:05:11 ERR Config unhandledRejection: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1549:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) [object Promise]
05:05:11 ERR Config ###########################
05:05:11 ERR Config ###########################
05:05:11 ERR Config unhandledRejection: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1549:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) [object Promise]
05:05:11 ERR Config ###########################
05:05:11 ERR Config process.on(unhandledRejection) promise.catch(Client network socket disconnected before secure TLS connection was established)
Config Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1549:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'api.chatie.io',
  port: 443,
  localAddress: undefined
}
05:05:11 ERR Config process.on(unhandledRejection) promise.catch(Client network socket disconnected before secure TLS connection was established)
Config Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1549:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'api.chatie.io',
  port: 443,
  localAddress: undefined
}
(node:42) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by why2lyj** [comment]
with latest version, issue fixed. Close issue.
