### ISSUE TITLE
我在推出微信后，更新了微信，然后报了这个错

### ISSUE THREAD

**Issue by A-Lang-Y** [padlocal/wechaty-puppet-padlocal#82]
15:17:07 ERR [PuppetPadlocal] login failed: VError: [tid:3fd8bc6c] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:3fd8bc6c] wechat bad request error: 你的微信版本过低，请升级至最新版本微信后再登录微信。点击“确定”后将跳转至最新版下载页面。
    at Request._failAllPendingRequest (/home/padplus/node_modules/padlocal-client-ts/src/Request.ts:309:15)
    at ClientDuplexStreamImpl.<anonymous> (/home/padplus/node_modules/padlocal-client-ts/src/Request.ts:72:12)
    at ClientDuplexStreamImpl.emit (events.js:375:28)
    at ClientDuplexStreamImpl.emit (domain.js:470:12)
    at Object.onReceiveStatus (/home/padplus/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/home/padplus/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /home/padplus/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
15:17:08 INFO [PuppetPadlocal] start login with type: QrLogin

**Comment by padlocal** [comment]
Please try again

**Comment by A-Lang-Y** [comment]
> Please try again
The problem has been solved. Thank you very much.
