### ISSUE TITLE
发送文件遇见这个错

### ISSUE THREAD

**Issue by A-Lang-Y** [padlocal/wechaty-puppet-padlocal#85]
msg_group
SubRequestCancelError [VError]: [tid:3bd79eca] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: 
    at Request._failAllPendingRequest (/alidata3/xiao-xin-bot/node_modules/padlocal-client-ts/src/Request.ts:309:15)
    at ClientDuplexStreamImpl.<anonymous> (/alidata3/xiao-xin-bot/node_modules/padlocal-client-ts/src/Request.ts:72:12)
    at ClientDuplexStreamImpl.emit (events.js:375:28)
    at ClientDuplexStreamImpl.emit (domain.js:470:12)
    at Object.onReceiveStatus (/alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  jse_shortmsg: '[tid:3bd79eca] request has been cancelled for reason: SERVER_ERROR',
  jse_cause: Error: 2 UNKNOWN: 
      at Object.callErrorFromStatus (/alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/call.ts:81:24)
      at Object.onReceiveStatus (/alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/client.ts:666:32)
      at Object.onReceiveStatus (/alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
      at /alidata3/xiao-xin-bot/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
      at processTicksAndRejections (internal/process/task_queues.js:77:11) {
    code: 2,
    details: '',
    metadata: Metadata { internalRepr: [Map], options: {} }

**Comment by A-Lang-Y** [comment]
?
